
services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: canvas
      POSTGRES_PASSWORD: canvas
      POSTGRES_DB: canvas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  board-api:
    build: ./board-api
    container_name: board-api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://canvas:canvas@localhost:5432/canvas
      APP_ENV: development
      SECRET_KEY: umHJYaN1l4Bmrpz6oI1RG6XHeG+g7O9YDQPJ1nt64Xc=
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      CORS_ORIGINS: 'http://localhost:5173,http://localhost:3000'

    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
